apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: typescript-ha-app-hpa
  labels:
    app: typescript-ha-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: typescript-ha-app
  minReplicas: 2 # Минимум для ночи
  maxReplicas: 4  # тесты показали, что держим в пике, мб стоило добавить 5, так как тесты != реальная нагрузка
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70  # 70% подкидываем новые
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90  # Так как память стабильна 90 норм
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600  # даём окно на стабилизацию 10 минут
      policies:
        - type: Pods
          value: 1  # дропаем 1 под за раз
          periodSeconds: 90
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - type: Pods
          value: 2  # можем поднять сразу 2 пода при необходимости
          periodSeconds: 60